

trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ci
    source: ci
    # trigger: 
    #   branches:
    #   - master

stages:
- stage: deploy_notebooks
  displayName: 'Deploy notebooks'
  jobs:
  - template: jobs/deploy-notebooks-job.yml
    parameters:
      environmentName: 'TEST'
      databricksDomain: '$(databricksDomain)'
      databricksToken: '$(databricksToken)'
      databricksNotebookPath: '$(databricksNotebookPath)'