# Azure Databricks Build Pipeline
# azure-pipelines.yml

trigger: none

pool:
  name: Hosted Ubuntu 1604

variables:
  basePath: 'single_tech_samples/databricks/sample4_ci_cd/notebook-dataframe'

steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(basePath)/notebooks'
    ArtifactName: 'notebooks'
  displayName: 'Publish Databricks notebooks'