parameters:
  - name: environmentName
    type: string

jobs:
  - deployment: deploy_dbx
    displayName: 'Deploy Basic Azure Databricks Environment'
    pool:
      vmImage: 'ubuntu-20.04'
    workspace:
      clean: all
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - bash: |
                bash single_tech_samples/databricks/sample1_basic_azure_databricks_environment/deploy.sh
              displayName: Deploy Basic Azure Databricks Environment
              workingDirectory: $(System.DefaultWorkingDirectory)
              env:
                  DEPLOYMENT_PREFIX: $(deploymentPrefix)
                  AZURE_SUBSCRIPTION_ID: $(azureSubscriptionID)
                  AZURE_RESOURCE_GROUP_NAME: $(azureResourceGroupName)
                  AZURE_RESOURCE_GROUP_LOCATION: $(parameters.azureResourceLocation)