# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  SLN_DIR: 'single_tech_samples\azuresql\ddo_samples_azuresql'
  SLN_NAME: 'ddo_samples_azuresql'
  SLN: '$(SLN_DIR)/$(SLN_NAME).sln'
  BUILD_PLATFORM: 'any cpu'
  BUILD_CONFIGURATION: 'release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install Nuget'

- task: NuGetCommand@2
  displayName: 'Restore Nuget packages'
  inputs:
    restoreSolution: '$(SLN)'

- task: VSBuild@1
  displayName: 'Build solution sln'
  inputs:
    solution: '$(SLN)'
    platform: '$(BUILD_PLATFORM)'
    configuration: '$(BUILD_CONFIGURATION)'

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    testAssemblyVer2: |
     $(SLN_DIR)\**\$(BUILD_CONFIGURATION)\*test*.dll
     !**\obj\**
    platform: '$(BUILD_PLATFORM)'
    configuration: '$(BUILD_CONFIGURATION)'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '$(SLN_DIR)\**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '$(SLN_DIR)\**\bin\$(BUILD_CONFIGURATION)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
