# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  SLN_DIR: 'samples\azuresql\ddo_samples_azuresql'
  BUILD_PLATFORM: 'any cpu'
  BUILD_CONFIGURATION: 'release'

steps:
- task: VSBuild@1
  displayName: 'Build solution sln'
  inputs:
    solution: '$(SLN_DIR)\ddo_samples_azuresql.sln'
    platform: '$(BUILD_PLATFORM)'
    configuration: '$(BUILD_CONFIGURATION)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     $(SLN_DIR)\**\$(BUILD_CONFIGURATION)\*test*.dll
     !**\obj\**
    platform: '$(BUILD_PLATFORM)'
    configuration: '$(BUILD_CONFIGURATION)'

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '$(SLN_DIR)\**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '$(SLN_DIR)\**\bin\$(BUILD_CONFIGURATION)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
