name: Custom Cred Scan
on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/credscan.yml

jobs:
  pattern_match_with_secrets:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        SECRET: ${{ secrets.ExcludeList }}
      run: (( $(grep -riE $SECRET . | wc -l) == 0 ))
